framework:
    asset_mapper:
        paths:
            assets/styles: styles
        missing_import_mode: strict

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
